name: KeinShin

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "@whyredisgod"

          replace: "@keinshin"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced New Username'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: whyred

          commit_user_email: poxsisofficial@gmail.com
